# -*- coding: utf-8 -*-
"""Kyle Costabile: Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LspQmPdWgoLJ3h6fUQNKR_z8Rz-GV6o

# Loading Packages and Importing Data Set
"""

#Loading packages and importing data set
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import gdown
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import RobustScaler
import plotly.express as px
import plotly.graph_objects
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree

file_id = '1BkRIlCeHvQvVGdJ0k7CI9JhJBqld29um'
download_url = f'https://drive.google.com/uc?id={file_id}'

output = 'diabetes_data.csv'
gdown.download(download_url, output, quiet=False)

diabetes_df = pd.read_csv(output)
diabetes_df

"""# Data Preprocessing"""

# Check for NA values
diabetes_df.isna().sum()

# Check for duplicate rows
total_duplicates = diabetes_df.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")

# dropping duplicates
diabetes_df.drop_duplicates(inplace=True)
diabetes_df.reset_index(drop=True, inplace=True)
diabetes_df

# Scaling the data using RobustScaler
numeric_features = diabetes_df[['Age', 'BMI', 'GenHlth', 'MentHlth', 'PhysHlth']].copy()
other_features = diabetes_df.drop(columns=['Age', 'BMI', 'GenHlth', 'MentHlth', 'PhysHlth']).copy()
scaler = RobustScaler()

# Numeric features scaled because scaling recoded categorical variables is redundant
data_scaled_array = scaler.fit_transform(numeric_features)
data_scaled_array
diabetes_df_scaled = diabetes_df
diabetes_df_numeric = pd.DataFrame(data_scaled_array, columns=numeric_features.columns)
diabetes_df_scaled['Age'] = diabetes_df_numeric['Age']
diabetes_df_scaled['BMI'] = diabetes_df_numeric['BMI']
diabetes_df_scaled['GenHlth'] = diabetes_df_numeric['GenHlth']
diabetes_df_scaled['MentHlth'] = diabetes_df_numeric['MentHlth']
diabetes_df_scaled['PhysHlth'] = diabetes_df_numeric['PhysHlth']
diabetes_df_scaled

"""# Exploratory Data Analysis"""

# Looking at data to see how each vallue differs between people with and without diabetes
# Most variables show little to no difference
fig, axes = plt.subplots(3, 6, figsize=(16, 8))
axes = axes.flatten()

features_list = diabetes_df_scaled.drop(columns=['Diabetes']).columns
for i, feat1 in enumerate(features_list):
    data = diabetes_df_scaled.groupby('Diabetes')[feat1].apply(list)
    axes[i].boxplot(data)
    axes[i].set_xlabel("Diabetes")
    axes[i].set_ylabel(feat1)
    axes[i].set_xticklabels(['No', 'Yes']) # Set x-tick labels for the categories

plt.suptitle("Boxplots of Scaled Features by Class")
plt.tight_layout()
plt.show()

"""# Creating Models"""

# Splitting Data
X = diabetes_df_scaled.drop(columns=['Diabetes'])
y = diabetes_df_scaled['Diabetes']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify = y)

"""Initialy I was going to use Random Forest as my model of choice"""

# Setting Up Random Forest
num_trees = 100
rf_model = RandomForestClassifier(
    n_estimators=num_trees,
    bootstrap=True,
    max_features='sqrt',
    random_state=42
)
rf_model.fit(X_train, y_train)

# Setting Up and Optimizing Decision Tree Model
base_model = DecisionTreeClassifier(random_state=42, class_weight='balanced')

tree_parameters = {
    'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
    'min_samples_split': [5,10,15,20]
}

grid_search = GridSearchCV(
    estimator=base_model,
    param_grid=tree_parameters,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_

best_params = grid_search.best_params_

print(best_params)

"""# Evaluating Models"""

rf_y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, rf_y_pred)
print("Random Forest Accuracy:", accuracy)

# Calculate accuracy for each individual tree
accuracies = []
for estimator in rf_model.estimators_:
    y_pred_tree = estimator.predict(X_test)
    accuracy_tree = accuracy_score(y_test, y_pred_tree)
    accuracies.append(accuracy_tree)

# Print accuracy for each individual tree
for tree_num, accuracy_tree in enumerate(accuracies, 1):
    print(f"Tree {tree_num} Accuracy: {accuracy_tree}")

#checking feature importance
individual_trees = rf_model.estimators_
tree_99 = individual_trees[99]

feature_importances = tree_99.feature_importances_

used_features = np.nonzero(feature_importances)[0]
used_features_names = X_train.columns[used_features]

tree_99_features_df = pd.DataFrame({
    'Feature': used_features_names,
    'Importance': feature_importances[used_features]
}).sort_values(by='Importance', ascending=False)

print(tree_99_features_df)

dt_y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, dt_y_pred)
print("Decision Tree Accuracy:", accuracy)

# Comparing models
def evaluate_model(name, y_true, y_pred):
    print(f"\n{name}")
    print(f"Accuracy : {accuracy_score(y_true, y_pred):.4f}")
    print(f"Precision: {precision_score(y_true, y_pred):.4f}")
    print(f"Recall   : {recall_score(y_true, y_pred):.4f}")
    print(f"F1-score : {f1_score(y_true, y_pred):.4f}")


evaluate_model("Random Forest", y_test, rf_y_pred)
evaluate_model("Grid Search", y_test, dt_y_pred)

"""Since using a standard decision tree optimized via grid search always seemed to outperform random forest I decided to go with that model instead.

# Final Model
"""

evaluate_model("Final Model Evaluation", y_test, dt_y_pred)

print("Graph of Decision Tree")
plt.figure(figsize=(60,40))
plot_tree(best_model, feature_names=X_train.columns,class_names=['No', 'Yes'],filled=True, rounded=True)
plt.show()

#User Input
age = int(input("age: "))
if age == 18 or age == 19:
    age = 1
elif age >= 80:
    age = 13
else:
    age = age // 5 - 3
sex = int(input("Sex(0 = female or 1 = male): "))
cholesterol = int(input("High Cholesterol? 0 = no 1 = yes: "))
checkChol = int(input("Have you checked your Cholesterol in the past 5 years? 0 = no 1 = yes: "))
bmi = float(input("BMI: "))
smoker = int(input("Have you smoked at least five packs worth of cigarettes in your life? 0 = no 1 = yes: "))
heartDisease = int(input("Coronary heart disease (CHD) or myocardial infarction (MI)? 0 = no 1 = yes: "))
physicalActivity = int(input("Have you been physical active in past 30 days - not including job? 0 = no 1 = yes: "))
fruits = int(input("Do you consoume 1+ fruits a day? 0 = no 1 = yes: "))
vegtables = int(input("Do you consoume 1+ vegtables a day? 0 = no 1 = yes: "))
if sex == 1:
    alcohol = int(input("Do you consoume 14+ drinks per week? 0 = no 1 = yes: "))
else:
    alcohol = int(input("Do you consoume 7+ drinks per week? 0 = no 1 = yes: "))
health = int(input("Would you say that in general your health is: scale 1-5, 1 = excellent, 2 = very good, 3 = good, 4 = fair, 5 = poor: "))
mental = int(input("days of poor mental health last month scale 1-30 days: "))
physical = int(input("physical illness or injury days in past 30 days scale 1-30: "))
walkDifficulty = int(input("Do you have serious difficulty walking or climbing stairs? 0 = no 1 = yes: "))
stroke = int(input("Have you ever had a stroke? 0 = no 1 = yes: "))
highbp = int(input("Do you have high blood pressure? 0 = no 1 = yes: "))

# Collect user input into a list
user_input_list = [
    age, sex, cholesterol, checkChol, bmi, smoker, heartDisease,
    physicalActivity, fruits, vegtables, alcohol, health, mental,
    physical, walkDifficulty, stroke, highbp
]

# Create a DataFrame from the user input, ensuring column names match X_train
user_input_df = pd.DataFrame([user_input_list], columns=X_train.columns)

example_pred = best_model.predict(user_input_df)
print("\nDiabetes Prediction: " + str(example_pred[0]))